#!/usr/bin/env python3
"""Templates for the scaffold generator. Token replacement (__TOKEN__) avoids
brace-escaping so template bodies are real, runnable code.

Every template bakes in a hard-won gotcha-fix so generated artifacts start
correct instead of re-learning the same lessons.
"""
from __future__ import annotations

import os

DAEMON_PY = '''#!/usr/bin/env python3
"""__NAME__ — daemon (generated by the arcturion-engineering scaffold skill).

Gotchas baked in (hard-won lessons):
  * runtime != source: installed as a LaunchAgent it runs from the install copy,
    not this repo path — edit source, then re-deploy (bootout -> bootstrap).
  * load gate: heavy work is skipped when an optional external check says the
    machine is overloaded (set __UPPER___LOAD_CHECK to an executable that exits 2
    to mean "too hot / too busy"; unset = always run).
  * idempotent: a pid lock prevents a second instance.
  * /health endpoint for universe health checks.
"""
from __future__ import annotations
import json, os, signal, subprocess, sys, threading, time
from http.server import BaseHTTPRequestHandler, HTTPServer

NAME = "__NAME__"
PORT = int(os.environ.get("__UPPER___PORT", "__PORT__"))
LOAD_CHECK = os.environ.get("__UPPER___LOAD_CHECK", "")
STATE_DIR = os.environ.get("__UPPER___STATE_DIR") or os.path.join(
    os.environ.get("XDG_STATE_HOME") or os.path.expanduser("~/.local/state"), NAME)
LOCK = os.path.join(STATE_DIR, f"{NAME}.pid")
_state = {"started": time.time(), "ticks": 0, "healthy": True}


def load_ok() -> bool:
    """Load gate. True unless the optional LOAD_CHECK command exits 2.
    No checker configured, or checker missing/failing -> assume ok."""
    if not LOAD_CHECK:
        return True
    try:
        return subprocess.run([LOAD_CHECK], capture_output=True, timeout=15).returncode != 2
    except Exception:
        return True


def _lock_pid_is_ours(pid: int) -> bool:
    # PID liveness alone is unsafe: after a reboot the OS reuses PIDs, so a stale
    # lock can point at an unrelated process and every respawn would exit
    # "already running". The lock counts only if the live PID is actually
    # running this script.
    if pid == os.getpid():
        return True
    try:
        os.kill(pid, 0)
    except (ProcessLookupError, PermissionError):
        return False
    try:
        out = subprocess.run(["ps", "-p", str(pid), "-o", "command="],
                             capture_output=True, text=True, timeout=5).stdout
    except Exception:
        return False
    return os.path.basename(__file__) in out


def acquire_lock() -> bool:
    os.makedirs(STATE_DIR, exist_ok=True)
    if os.path.exists(LOCK):
        try:
            pid = int(open(LOCK).read().strip())
        except ValueError:
            pid = -1
        if pid > 0 and _lock_pid_is_ours(pid):
            return False  # already running
        try:
            os.remove(LOCK)  # stale: dead, reused-by-another-process, or garbage
        except OSError:
            pass
    with open(LOCK, "w") as fh:
        fh.write(str(os.getpid()))
    return True


def release_lock():
    try:
        os.remove(LOCK)
    except OSError:
        pass


class Health(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path.rstrip("/") in ("/health", ""):
            body = json.dumps({"name": NAME, "ok": _state["healthy"],
                               "uptime_s": round(time.time() - _state["started"], 1),
                               "ticks": _state["ticks"]}).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            self.send_response(404)
            self.end_headers()

    def log_message(self, *a):
        pass


def serve_health():
    HTTPServer(("127.0.0.1", PORT), Health).serve_forever()


def work_tick():
    """Replace with real work. Skipped when the load gate says no."""
    if not load_ok():
        return
    _state["ticks"] += 1


def main() -> int:
    if not acquire_lock():
        print(f"{NAME} already running", file=sys.stderr)
        return 0
    signal.signal(signal.SIGTERM, lambda *_: (release_lock(), sys.exit(0)))
    threading.Thread(target=serve_health, daemon=True).start()
    try:
        while True:
            work_tick()
            time.sleep(int(os.environ.get("__UPPER___INTERVAL", "60")))
    finally:
        release_lock()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

DAEMON_PLIST = '''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated (macOS launchd). Install:
       launchctl bootout gui/$UID/com.example.__NAME__ 2>/dev/null || true
       launchctl bootstrap gui/$UID THIS.plist
     NEVER edit a live plist in place; always bootout -> modify -> bootstrap.
     runtime != source: point ProgramArguments at the INSTALLED copy. -->
<plist version="1.0"><dict>
  <key>Label</key><string>com.example.__NAME__</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string><string>-lc</string>
    <string>exec python3 "__INSTALL_PATH__/__NAME__.py"</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>__LOG_DIR__/__NAME__.out.log</string>
  <key>StandardErrorPath</key><string>__LOG_DIR__/__NAME__.err.log</string>
</dict></plist>
'''

DAEMON_TEST = '''#!/usr/bin/env python3
import os, sys, tempfile, unittest
os.environ["__UPPER___STATE_DIR"] = tempfile.mkdtemp(prefix="__NAME___state_")  # keep the test hermetic
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import __NAME__ as d


class T(unittest.TestCase):
    def test_load_ok_returns_bool(self):
        self.assertIn(d.load_ok(), (True, False))

    def test_lock_cycle_is_idempotent(self):
        self.assertTrue(d.acquire_lock())
        self.assertFalse(d.acquire_lock())  # second instance blocked
        d.release_lock()
        self.assertTrue(d.acquire_lock())
        d.release_lock()

    def test_health_state_shape(self):
        self.assertIn("healthy", d._state)


if __name__ == "__main__":
    unittest.main(verbosity=2)
'''

DAEMON_README = '''# __NAME__ (generated daemon)

macOS launchd example. On Linux, wrap `python3 __NAME__.py` in a systemd unit instead; the daemon itself is portable.
Rename the `com.example` label to your own reverse-DNS prefix before installing.

Install (bootout -> bootstrap; never edit a live plist in place):
```
cp __NAME__.py <INSTALL_DIR>/        # runtime != source: run the installed copy
launchctl bootout gui/$UID/com.example.__NAME__ 2>/dev/null || true
launchctl bootstrap gui/$UID com.example.__NAME__.plist
curl -fsS localhost:__PORT__/health  # verify
```
Test: `python3 tests/test___NAME__.py`
'''

MCP_PY = '''#!/usr/bin/env python3
"""__NAME__ MCP server stub (stdio JSON-RPC 2.0, zero deps). Generated by the arcturion-engineering scaffold skill."""
from __future__ import annotations
import json, sys

TOOLS = [{"name": "ping", "description": "Echo a message.",
          "inputSchema": {"type": "object",
                          "properties": {"msg": {"type": "string"}},
                          "required": ["msg"]}}]


def handle(req: dict):
    mid, method = req.get("id"), req.get("method")
    if method == "initialize":
        return {"jsonrpc": "2.0", "id": mid, "result": {
            "protocolVersion": "2024-11-05", "capabilities": {"tools": {}},
            "serverInfo": {"name": "__NAME__", "version": "0.1.0"}}}
    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": mid, "result": {"tools": TOOLS}}
    if method == "tools/call":
        p = req.get("params", {})
        if p.get("name") == "ping":
            text = f"pong: {p.get('arguments', {}).get('msg', '')}"
            return {"jsonrpc": "2.0", "id": mid,
                    "result": {"content": [{"type": "text", "text": text}]}}
        return {"jsonrpc": "2.0", "id": mid,
                "error": {"code": -32601, "message": f"unknown tool {p.get('name')}"}}
    if method and method.startswith("notifications/"):
        return None
    return {"jsonrpc": "2.0", "id": mid,
            "error": {"code": -32601, "message": f"unknown method {method}"}}


def main() -> int:
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            req = json.loads(line)
        except ValueError:
            continue
        resp = handle(req)
        if resp is not None:
            sys.stdout.write(json.dumps(resp) + "\\n")
            sys.stdout.flush()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

MCP_TEST = '''#!/usr/bin/env python3
import os, sys, unittest
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import __NAME__ as m


class T(unittest.TestCase):
    def test_initialize(self):
        r = m.handle({"jsonrpc": "2.0", "id": 1, "method": "initialize"})
        self.assertEqual(r["result"]["serverInfo"]["name"], "__NAME__")

    def test_tools_list(self):
        r = m.handle({"jsonrpc": "2.0", "id": 2, "method": "tools/list"})
        self.assertTrue(any(t["name"] == "ping" for t in r["result"]["tools"]))

    def test_ping_call(self):
        r = m.handle({"jsonrpc": "2.0", "id": 3, "method": "tools/call",
                      "params": {"name": "ping", "arguments": {"msg": "hi"}}})
        self.assertIn("pong: hi", r["result"]["content"][0]["text"])

    def test_unknown_method_errors(self):
        self.assertIn("error", m.handle({"jsonrpc": "2.0", "id": 4, "method": "bogus"}))


if __name__ == "__main__":
    unittest.main(verbosity=2)
'''

CLI_PY = '''#!/usr/bin/env python3
"""__NAME__ — CLI tool (generated by the arcturion-engineering scaffold skill).

Secrets come ONLY from environment variables (never hardcoded, never passed as
CLI arguments where they'd land in shell history or `ps`). Set the variable
named by SECRET_ENV before running, e.g.:  export __UPPER___API_TOKEN=...
"""
from __future__ import annotations
import argparse, os, sys

SECRET_ENV = "__UPPER___API_TOKEN"


def get_secret(env_var: str = SECRET_ENV) -> str:
    """Read a secret from the environment; fail loudly (without echoing it) if absent."""
    value = os.environ.get(env_var, "")
    if not value:
        raise RuntimeError(f"{env_var} is not set")
    return value


def run(args) -> int:
    if args.check_secret:
        try:
            get_secret()
        except RuntimeError as e:
            print(f"__NAME__: {e}", file=sys.stderr)
            return 1
        print(f"__NAME__: {SECRET_ENV} is set")  # never print the value
    else:
        print(f"__NAME__: ok (value={args.value})")
    return 0


def build_parser():
    ap = argparse.ArgumentParser(prog="__NAME__")
    ap.add_argument("--value", default=None)
    ap.add_argument("--check-secret", action="store_true",
                    help=f"verify that {SECRET_ENV} is set (does not print it)")
    return ap


def main() -> int:
    return run(build_parser().parse_args())


if __name__ == "__main__":
    raise SystemExit(main())
'''

CLI_TEST = '''#!/usr/bin/env python3
import os, sys, unittest
from unittest import mock
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import __NAME__ as c


class T(unittest.TestCase):
    def test_runs_without_secret(self):
        self.assertEqual(c.run(c.build_parser().parse_args(["--value", "x"])), 0)

    def test_secret_present(self):
        with mock.patch.dict(os.environ, {c.SECRET_ENV: "S3CRET"}):
            self.assertEqual(c.run(c.build_parser().parse_args(["--check-secret"])), 0)

    def test_secret_missing_fails_cleanly(self):
        env = {k: v for k, v in os.environ.items() if k != c.SECRET_ENV}
        with mock.patch.dict(os.environ, env, clear=True):
            self.assertEqual(c.run(c.build_parser().parse_args(["--check-secret"])), 1)


if __name__ == "__main__":
    unittest.main(verbosity=2)
'''

SKILL_MD = '''---
name: __NAME__
description: TODO — describe precisely when this skill should trigger.
---

# __NAME__

TODO. Generated by the arcturion-engineering scaffold skill.

## Use
```
python3 <skill>/scripts/main.py
```
Test: `python3 tests/test_main.py`
'''

SKILL_MAIN = '''#!/usr/bin/env python3
"""__NAME__ skill entrypoint (generated)."""


def main():
    print("__NAME__ ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
'''

SKILL_TEST = '''#!/usr/bin/env python3
import os, sys, unittest
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "scripts"))
import main as m


class T(unittest.TestCase):
    def test_main_runs(self):
        self.assertEqual(m.main(), 0)


if __name__ == "__main__":
    unittest.main(verbosity=2)
'''


def _sub(tmpl: str, name: str, port: int = 8790, install_path: str = "", log_dir: str = "") -> str:
    return (
        tmpl.replace("__NAME__", name)
        .replace("__UPPER__", name.upper())
        .replace("__PORT__", str(port))
        .replace("__INSTALL_PATH__", install_path or "<INSTALL_DIR>")
        .replace("__LOG_DIR__", log_dir or os.path.expanduser(f"~/Library/Logs/{name}"))
    )


def render(kind: str, name: str, base: str, port: int):
    """Return [(path, content, executable_bool), ...] for the given kind."""
    if kind == "daemon":
        return [
            (os.path.join(base, f"{name}.py"), _sub(DAEMON_PY, name, port, install_path=base), True),
            (os.path.join(base, f"com.example.{name}.plist"), _sub(DAEMON_PLIST, name, port, install_path=base), False),
            (os.path.join(base, "README.md"), _sub(DAEMON_README, name, port), False),
            (os.path.join(base, "tests", f"test_{name}.py"), _sub(DAEMON_TEST, name), True),
        ]
    if kind == "mcp":
        return [
            (os.path.join(base, f"{name}.py"), _sub(MCP_PY, name), True),
            (os.path.join(base, "tests", f"test_{name}.py"), _sub(MCP_TEST, name), True),
        ]
    if kind == "cli":
        return [
            (os.path.join(base, f"{name}.py"), _sub(CLI_PY, name), True),
            (os.path.join(base, "tests", f"test_{name}.py"), _sub(CLI_TEST, name), True),
        ]
    if kind == "skill":
        return [
            (os.path.join(base, "SKILL.md"), _sub(SKILL_MD, name), False),
            (os.path.join(base, "scripts", "main.py"), _sub(SKILL_MAIN, name), True),
            (os.path.join(base, "tests", "test_main.py"), _sub(SKILL_TEST, name), True),
        ]
    raise ValueError(f"unknown kind: {kind}")
